### PR TITLE
cli: fixes testing for `ConnectionError` in `get_appointment`

### PR DESCRIPTION
**Pull request by bjarnemagnussen**
It seems that the test for `test_get_appointment_err` was ignoring checking for `ConnectionError` as the mocked request was not actually polled by `teos_cli`, because the randomly generated locator was not added to the mocked request. 

This also fixes calling the `ConnectionError` function, which was unimported.

### CODE REVIEW

**Comment by bjarnemagnussen** [comment]
Ouch, indeed! I have rebased to the current master. Hope that is better?

**Comment by sr-gi** [comment]
Hey @bjarnemagnussen , we require commits to be signed in PR (I guess I should add this to [CONTRIBUTING](https://github.com/talaia-labs/python-teos/blob/master/CONTRIBUTING.md)).

Since this is just changing a small part of a test I can accept it without signing, but if you'd like to contribute further, and you are very welcome to, I'd suggest you enable commit signing on GitHub: https://help.github.com/en/github/authenticating-to-github/signing-commits

I can either merge myself or wait for you to do it (it'll require enable signing, rebase with a signed commit and merge). What would you prefer?

**Comment by bjarnemagnussen** [comment]
Alright! I will look into signing to have it correctly set up and recommit!

**Comment by sr-gi** [comment]
Sweet! Now it looks good :)

**Comment by sr-gi** [comment]
You should be able to merge. Let me know otherwise.

**Comment by bjarnemagnussen** [comment]
The button to merge doesn't appear. But you can just go ahead and merge :)

**Pull request merged**
