### PR TITLE
Clean up apt caches in docker image

### PR DESCRIPTION
**Pull request by 3nprob**
Removes unnecessary apt caches from final docker image

### CODE REVIEW

**Comment by sr-gi** [comment]
LGTM.

As a matter of curiosity, have you checked what is the size reduction by removing the tmp files and not installing the recommended packages?

**Comment by 3nprob** [comment]
Honestly no; just noticed it as low-hanging fruit as I set it up :)

**Review by sr-gi — APPROVED** [review]

**Comment by sr-gi** [comment]
Hey @3nprob, saw you requested a review on this again. This has already been approved, will merged it to master asap.

**Comment by sr-gi** [comment]
Just an update on this. I haven't merged yet since I'm trying to port the same changes to the arm32 and arm64 images, but testing is proving to be quite time consuming.

Just a nit, would you mind rebasing and formatting lines 5-8 with a tab (4 spaces) instead of 2 spaces? I'll do it myself otherwise once I add the changes to the other two Dockerfiles.

**Comment by 3nprob** [comment]
Thanks for the update :)
Rebased and amended

**Comment by sr-gi** [comment]
I've applied the changes to the arm based images.

However, there's an issue with grpcio for `arm32v7` that makes `teos` to crash when built via docker using `grpcio==1..37.0` (see #287). I'm going to leave this open for a couple more days just in case I can get some feedback about it and try to squeeze the fix. Otherwise I'll merge and deal with it before the next release.

**Comment by sr-gi** [comment]
@3nprob I'm going to finally merge this given the issue has not been patched yet by the gRPC guys. I'll deal with that specific issue before the next release.

Would you mind rebasing for the last time?

**Comment by 3nprob** [comment]
@sr-gi rebased

**Review by sr-gi — APPROVED** [review]

**Pull request merged**
