### PR TITLE
Adds c-lightning options to plugin

### PR DESCRIPTION
**Pull request by sr-gi**
The plugin can now be configured with c-lightning options, meaning that the config parameters can be set on the c-lightning config file so no standalone config file is required.

For now, the standalone config file is left, so both options are available. The current priority is: c-lightning conf, standalone conf, defaults.

Related to #268

### CODE REVIEW

**Comment by sr-gi** [comment]
@3nprob would you mind trying this? It enables the c-lightning options you requested.

**Comment by 3nprob** [comment]
This looks great, will try and report ack @sr-gi  :)

**Comment by sr-gi** [comment]
Hey @3nprob, did you give it a go? No rush if not, just checking the state of the open PRs.

**Comment by 3nprob** [comment]
Apologies for the delay - yes it works fine , thanks for your work :)

**Pull request merged**
